In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('C:/Users/Zhangchensi/bootcamp_Chensi_Zhang/project/data/processed/processed_data.csv')
df = df.iloc[:,1:]
df

          open      high       low     close    volume  year
0     0.050354  0.046686  0.043518  0.045676  0.130251  2015
1     0.043057  0.040097  0.038797  0.038268  0.164745  2015
2     0.038937  0.037216  0.036898  0.038292  0.169450  2015
3     0.040491  0.039035  0.041924  0.041876  0.089477  2015
4     0.045269  0.048362  0.046804  0.051834  0.149426  2015
...        ...       ...       ...       ...       ...   ...
2668  0.332094  0.338466  0.343085  0.343933  0.182155  2025
2669  0.339121  0.338749  0.344107  0.342610  0.126241  2025
2670  0.338991  0.336765  0.340420  0.339747  0.139073  2025
2671  0.333577  0.334026  0.342306  0.338064  0.081290  2025
2672  0.332576  0.333436  0.340457  0.337270  0.087287  2025

[2673 rows x 6 columns]

In [3]:
df['ln_open'] = np.log1p(df['open']) #dealing with right-skewed
df['ln_close'] = np.log1p(df['close']) #dealing with right-skewed
df['ln_high'] = np.log1p(df['high']) #dealing with right-skewed
df['ln_low'] = np.log1p(df['low']) #dealing with right-skewed

In [5]:
df['open/close'] = df['open'] / df['close'] #capturing relative behavior, not absolute values,creating a stronger and more interpretable feature,mitigating multicollinearity issues.
df['high/low'] = df['high'] / df['low'] #capturing relative behavior, not absolute values,creating a stronger and more interpretable feature,mitigating multicollinearity issues.